Add mdns browser
ci4rail/io4edge-client-go pull request #3
Opened 2021-09-23 14:23 UTC by FranziskaKnoedtel

2021-09-23 18:36 UTC, KlausPopp requested changes

2021-09-23 18:36 UTC, KlausPopp commented on core/mdns_browser.go
> +func GetAddressFromService(instanceName string, serviceName string, timeout int) (string, uint16, error) {
Install pre-commit-hooks. 
If they are installed, they would warn you that the function comment must begin with the function name:
// GetAddressFromService queries mdns for the requested....
What exactly has to be passed to instanceName and serviceName? Can I specify the protocol (tcp/udp)?

2021-09-23 18:36 UTC, KlausPopp commented on core/mdns_browser.go
> +		log.Fatalf("Cannot get system bus: %v", err)
You are in a package. Never exit from a function in a package. Leave this up to the package user whether to treat this as a fatal error!

2021-09-23 18:36 UTC, KlausPopp commented on core/mdns_browser.go
> +		log.Fatalf("Avahi new failed: %v", err)
You are in a package. Never exit from a function in a package. Leave this up to the package user whether to treat this as a fatal error!

2021-09-23 18:36 UTC, KlausPopp commented on core/mdns_browser.go
> +		log.Fatalf("ServiceBrowserNew() failed: %v", err)
You are in a package. Never exit from a function in a package. Leave this up to the package user whether to treat this as a fatal error!

2021-09-23 18:36 UTC, KlausPopp commented on core/mdns_browser.go
> +				log.Fatalf("ResolveService() failed: %v", err)
You are in a package. Never exit from a function in a package. Leave this up to the package user whether to treat this as a fatal error!

2021-09-23 18:38 UTC, KlausPopp commented
Please add in core: NewClientFromService() function (That calls the previous NewClientFromSocketAddress).
Update Examples in README

2021-10-04 10:46 UTC, batthebee commented on README.md
> +### Connect to a Target with service name
Add system dependencies to readme, like dbus.

2021-11-09 10:03 UTC, KlausPopp approved these changes

2021-11-09 10:04 UTC, merged