UDP Server and Tracelet API - WIP
ci4rail/io4edge-client-go pull request #83
Opened 2024-07-24 15:39 UTC by FranziskaKnoedtel

Added UDP Socket implementation.
Added FrameHandshake implementation.
Changed channels ReadMsg() implementation (fix timeout handling that blocking read does not continue on timeout)

2024-08-14 14:49 UTC, KlausPopp requested changes

2024-08-14 14:49 UTC, KlausPopp commented on server/udp_server.go
> +// NewServer creates a new function client from a socket with the specified address.
rename to NewUDPServer to distinguish from future TCP Server

2024-08-14 14:49 UTC, KlausPopp commented on tracelet/stream_server.go
> +func NewTraceletServer(port string, timeout time.Duration) *Server {
rename to NewTraceletUDPServer

why is port a string?

2024-08-14 14:49 UTC, KlausPopp commented on tracelet/stream_server.go
> +type Server struct {
rename to UDPServer

2024-08-14 14:49 UTC, KlausPopp commented on tracelet/stream_server.go
> +					log.Errorf("Error matching pattern: %v", err)
This is no error. It only means that noone has subscribed

2024-08-14 14:49 UTC, KlausPopp commented on tracelet/stream_server.go
> +	log.Printf("Closing connection")
Change to Debug

2024-08-14 14:49 UTC, KlausPopp commented on tracelet/stream_server.go
> +		log.Printf("Read timeout -> close socket")
Change to debug

2024-08-14 14:49 UTC, KlausPopp commented on transport/socket/udp_socket.go
> +var ReadBufferSize = 10
Is this intentionally exported? Better use const

2024-08-14 14:49 UTC, KlausPopp commented on transport/socket/udp_socket.go
> +				select {
DRY: factor out duplicate code

2024-08-15 09:38 UTC, FranziskaKnoedtel commented on transport/frame.go
> +		netErr, ok := err.(net.Error)
I did the error handling according to: https://go.dev/blog/error-handling-and-go#the-error-type
There is an example for how to handle errors of the net package.

2024-08-15 09:43 UTC, FranziskaKnoedtel commented on examples/tracelet/specific_tracelet/main.go
> +	go catchTracelet1Stream(server.Subscribe("TRACELET-1"))
The regex bounderies are added now internally in Subscribe() to the pattern.

2024-08-15 10:23 UTC, KlausPopp approved these changes

2024-08-16 14:05 UTC, merged